name: ML CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # -----------------------
  # JOB 1: TRAIN (CI)
  # -----------------------
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train model
      run: |
        python scripts/train.py

    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          model.joblib
          metrics.json

  # -----------------------
  # JOB 2: DEPLOY (CD)
  # -----------------------
  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts

    - name: Compare metrics
      run: |
        CURR_MSE=$(jq -r '.mse' metrics.json)
        BEST_MSE=${{ vars.BEST_MSE }}

        echo "Current MSE: $CURR_MSE"
        echo "Best MSE: $BEST_MSE"

        python <<EOF
        import sys

        curr = float("$CURR_MSE")
        best = float("$BEST_MSE")

        if curr >= best:
            print("2022BCS0175----Metric did not improve")
            sys.exit(0)
        else:
            print("Metric improved, proceeding to deploy")
        EOF

        echo "DEPLOY=true" >> $GITHUB_ENV


    - name: Login to Docker Hub
      if: env.DEPLOY == 'true'
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
        -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build Docker image
      if: env.DEPLOY == 'true'
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/2022bcs0175-wine-api:latest .

    - name: Push Docker image
      if: env.DEPLOY == 'true'
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/2022bcs0175-wine-api:latest
